spring:
  application:
    name: catalog-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

opentracing:
  jaeger:
    log-spans: true
    http-sender:
      url: http://localhost:14268/api/traces
