apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: catalog-service-pipeline
    name: catalog-service-pipeline
  name: catalog-service-pipeline
spec:
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/marzelwidmer/catalog-service.git
    sourceSecret:
      name: ci-user-at-github
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile

